require("dotenv").config()
const express = require("express")
const bodyParser = require("body-parser")
const socketio = require("socket.io")
const route = require("./route/route")
const api = require("./api/api")

const server = express()
server.use(bodyParser.json())
server.set("view engine", "ejs")
server.use(express.static(__dirname))
route(server)
api(server)
const listen = server.listen(5890, () => console.log("5890"))
const io = socketio.listen(listen)
